// @ts-check
import { defineConfig } from "astro/config";
import mdx from "@astrojs/mdx";
import tailwindcss from "@tailwindcss/vite";

const SITE = "https://specification.website";

// Sitemaps are generated by per-category endpoints under src/pages/sitemap-*.xml.ts
// instead of @astrojs/sitemap, so each category gets its own file and the index
// can be reported on separately in Search Console.

// https://astro.build/config
export default defineConfig({
  site: SITE,
  integrations: [mdx()],
  vite: {
    plugins: [tailwindcss()],
  },
  server: {
    port: 31337,
    host: true,
  },
  markdown: {
    shikiConfig: {
      theme: "github-light-default",
      wrap: true,
    },
  },
  build: {
    inlineStylesheets: "auto",
  },
});
